global:

route:
  receiver: 'default'
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 1s
  group_by: [cluster, alertname]
  # All alerts that do not match the following child routes
  # will remain at the root node and be dispatched to 'default-receiver'.

  routes:
  - match:
      alertname: HighRateRequest

# Setup the default receiver to send a POST message
# to localhost:8080 whenever triggered
receivers:
- name: 'default'
  webhook_configs:
  - send_resolved: true
    url: 'http://localhost:8080'
